
---
# https://cdn.sparkfun.com/assets/0/b/0/f/7/u-blox8-M8_ReceiverDescrProtSpec__UBX-13003221__Public.pdf
# Section: 32.18.14 UBX-NAV-PUT (0x01 0x07)
# 32.18.14.1 Navigation Position Velocity Time Solution
uint32   iTOW
uint8    year
uint8    month
uint8    day
uint8    hour
uint8    min
uint8    sec
uint8    valid
uint32   tAcc
int32    nano

uint8    fixType
uint8    flags
uint8    flags2
uint8    numSV

float64  lon
float64  lat
int32    height
int32    hMSL
uint32   hAcc
uint32   vAcc
int32    velN
int32    velE
int32    velD
int32    gSpeed
float64  headMot
uint32   sAcc
float64  headAcc
float64  pDOP
uint8[6] reserved1
float64  headVeh
float64  magDec
float64  magAcc
